// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../good.js/auth/login.js', ['good.auth', 'good.auth.login'], ['good.net.CrossDomainRpc', 'goog.Uri', 'goog.Uri.QueryData', 'goog.dom', 'goog.events']);
goog.addDependency('../../../good.js/auth/signup.js', ['good.auth.signup'], ['good.net.CrossDomainRpc', 'goog.dom', 'goog.events']);
goog.addDependency('../../../good.js/net/crossdomainrpc.js', ['good.net.CrossDomainRpc'], ['goog.json']);
